from typing import Dict, List
from ..Constants import ItemNames, LocationNames


# Connection Types: Stairs, Shortcut, Dungeon

# floor_order: has ordered list of floors, each with {"Floors": region, "Connections": [], "Last_Smiler": "", "Last_Interface": "", "Chest_Score": 0, "Access_Cost": 0, "Accessible": False}

# RequiredBranes = all brand rooms, all mural rooms, tail's room, gor's room, room 0, etc

# reorganize to be modular, with each room pack it's own modular file
# maybe each floor pack has a type? Like, some might be entire domains unshuffled, and it just swaps the domain in for another domain?
# others might be party collections of various floor types
# keep it at 8 brand carves per seed, but maybe allow more than 8 rooms?

# RequiredMainBranes
# FillerMainBranes
# RequiredSideBranes
# FillerSideBranes
# Brand Rooms
# ImportantBranes? (include all or none)

VanillaBraneOrder = [
        "B000","B001","B002","B003","B004","B005","B006","B007","B008","B009","B010","B011","B012","B013","B014","B015","B016","B017","B018","B019",
        "B020","B021","B022","B023","B024","B025","B026","B027","B028","B029","B030","B031","B032","B033","B034","B035","B036","B037","B038","B039",
        "B040","B041","B042","B043","B044","B045","B046","B047","B048","B049","B050","B051","B052","B053","B054","B055","B056","B057","B058","B059",
        "B060","B061","B062","B063","B064","B065","B066","B067","B068","B069","B070","B071","B072","B073","B074","B075","B076","B077","B078","B079",
        "B080","B081","B082","B083","B084","B085","B086","B087","B088","B089","B090","B091","B092","B093","B094","B095","B096","B097","B098","B099",
        "B100","B101","B102","B103","B104","B105","B106","B107","B108","B109","B110","B111","B112","B113","B114","B115","B116","B117","B118","B119",
        "B120","B121","B122","B123","B124","B125","B126","B127","B128","B129","B130","B131","B132","B133","B134","B135","B136","B137","B138","B139",
        "B140","B141","B142","B143","B144","B145","B146","B147","B148","B149","B150","B151","B152","B153","B154","B155","B156","B157","B158","B159",
        "B160","B161","B162","B163","B164","B165","B166","B167","B168","B169","B170","B171","B172","B173","B174","B175","B176","B177","B178","B179",
        "B180","B181","B182","B183","B184","B185","B186","B187","B188","B189","B190","B191","B192","B193","B194","B195","B196","B197","B198","B199",
        "B200","B201","B202","B203","B204","B205","B206","B207","B208","B209","B210","B211","B212","B213","B214","B215","B216","B217","B218","B219",
        "B220","B221","B222","B223","B224","B225","B226","B227","B228","B229","B230","B231","B232","B233","B234","B235","B236","B237","B238","B239",
        "B240","B241","B242","B243","B244","B245","B246","B247","B248","B249","B250","B251","B252","B253","B254","B255"]


# for adding new brand rooms and carvings:
# if key exists in brand_dictionary, append the new carve (from a table of all carves of this new brand) to it's list of possible carves

# can dev and trailer brands be carved in eus' room?
# also add elysum carving, etc

VanillaBrandConnections = {
        "add": "room_add",
        "eus": "room_eus",
        "bee": "room_bee",
        "mon": "room_mon",
        "tan": "room_tan",
        "gor": "room_gor",
        "lev": "room_lev",
        "cif": "room_cif",
        "dis": "room_dis"}

VanillaBrandCarving = {
        "B023": [("room_add",[[("brand","add"),]]),
                 ("room_gor",[[("brand","gor"),("item", ItemNames.endless_void_rod)]]),
                 ("room_lev",[[("brand","lev"),("item", ItemNames.endless_void_rod)]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.endless_void_rod)]])],
        "B053": [("room_add",[[("brand","add"),("item", ItemNames.void_wings)]]),
                 ("room_eus",[[("brand","eus"),]]),
                 ("room_bee",[[("brand","bee"),("item", ItemNames.void_wings)]]),
                 ("room_tan",[[("brand","tan"),("item", ItemNames.void_wings)]]),
                 ("room_lev",[[("brand","lev"),]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.void_wings)]])],
        "B067": [("room_add",[[("brand","add"),("item", ItemNames.endless_void_rod)]]),
                 ("room_bee",[[("brand","bee"),]]),
                 ("room_gor",[[("brand","gor"),("item", ItemNames.endless_void_rod)]]),
                 ("room_lev",[[("brand","lev"),("item", ItemNames.endless_void_rod)]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.endless_void_rod)]])],
        "B089": [("room_add",[[("brand","add"),("item", ItemNames.endless_void_rod)]]),
                 ("room_eus",[[("brand","eus"),]]),
                 ("room_bee",[[("brand","bee"),("item", ItemNames.endless_void_rod)]]),
                 ("room_mon",[[("brand","mon"),]]),
                 ("room_tan",[[("brand","tan"),]]),
                 ("room_lev",[[("brand","lev"),("item", ItemNames.endless_void_rod)]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.endless_void_rod)]])],
        "B137": [("room_add",[[("brand","add"),("item", ItemNames.endless_void_rod)]]),
                 ("room_eus",[[("brand","eus"),("item", ItemNames.void_sword)]]),
                 ("room_bee",[[("brand","bee"),("item", ItemNames.endless_void_rod)]]),
                 ("room_mon",[[("brand","mon"),("item", ItemNames.endless_void_rod)]]),
                 ("room_tan",[[("brand","tan"),]]),
                 ("room_gor",[[("brand","gor"),("item", ItemNames.endless_void_rod)]]),
                 ("room_lev",[[("brand","lev"),("item", ItemNames.endless_void_rod)]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.endless_void_rod)]])],
        "B157": [("room_add",[[("brand","add"),]]),
                 ("room_eus",[[("brand","eus"),]]),
                 ("room_bee",[[("brand","bee"),]]),
                 ("room_mon",[[("brand","mon"),]]),
                 ("room_tan",[[("brand","tan"),]]),
                 ("room_gor",[[("brand","gor"),]]),
                 ("room_lev",[[("brand","lev"),]]),
                 ("room_cif",[[("brand","cif"),]])],
        "B179": [("room_lev",[[("brand","lev"),]])],
        "B223": [("room_cif",[[("brand","cif"),]])],
        "B227": [("room_add",[[("brand","add"),("item", ItemNames.void_wings),("item", ItemNames.void_sword)]]),
                 ("room_eus",[[("brand","eus"),("item", ItemNames.void_wings),("item", ItemNames.void_sword)]]),
                 ("room_bee",[[("brand","bee"),("item", ItemNames.void_wings),("item", ItemNames.void_sword)]]),
                 ("room_mon",[[("brand","mon"),("item", ItemNames.void_wings),("item", ItemNames.void_sword)]]),
                 ("room_tan",[[("brand","tan"),("item", ItemNames.void_wings),("item", ItemNames.void_sword)]]),
                 ("room_gor",[[("brand","gor"),("item", ItemNames.endless_void_rod)]]),
                 ("room_lev",[[("brand","lev"),("item", ItemNames.endless_void_rod)]]),
                 ("room_cif",[[("brand","cif"),("item", ItemNames.endless_void_rod)]]),
                 ("room_dis",[[("brand","dis"),("item", ItemNames.endless_void_rod)]])],
        }

RequiredMainBranes = {
        "B000": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B001": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        # murals
        "B029": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","add")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B057": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","eus")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B085": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","bee")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B113": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","mon")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B141": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","tan")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B169": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","gor")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B197": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","lev")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B225": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[("brand","cif")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        # brand rooms
        "B023": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B053": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B067": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B089": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B137": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B157": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B179": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B223": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": True },
        "B227": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": True,  "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        # mon floors
        "B004": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B044": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B086": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B124": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B196": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        }

# B077's locust chest can be tripled and obtained without burdens, but then the exit cannot be reached.
# Thus, logic expects you to triple it and then die, resulting in a chest_score of 2.
OptionalMainBranes = {
        "B002": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B003": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B005": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B006": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B007": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": [("mon_shortcut_1",[[]])], "Dungeon": False, "Skipped": False},
        "B008": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B009": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B010": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B011": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B012": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B013": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B014": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B015": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B016": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B017": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B018": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B019": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B020": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B021": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B022": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B024": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B025": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B026": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B027": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B028": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B030": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B031": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B032": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B033": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B034": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B035": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B036": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B037": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": [("mon_shortcut_2",[[]])], "Dungeon": False, "Skipped": False},
        "B038": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B039": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B040": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B041": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B042": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B043": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B045": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B046": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B047": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B048": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B049": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B050": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B051": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B052": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B054": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B055": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B056": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B058": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B059": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B060": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B061": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B062": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B063": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B064": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B065": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B066": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B068": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B069": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B070": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B071": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B072": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B073": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B074": {"Chest_Score": 3, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B075": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B076": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B077": {"Chest_Score": 2, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B078": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B079": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B080": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B081": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B082": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B083": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": [("mon_shortcut_3",[[]])], "Dungeon": False, "Skipped": False},
        "B084": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B087": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B088": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B090": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B091": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B092": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B093": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B094": {"Chest_Score": 1, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B095": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B096": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B097": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B098": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B099": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B100": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B101": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B102": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B103": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B104": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B105": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B106": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B107": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B108": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B109": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B110": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B111": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B112": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B114": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B115": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B116": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B117": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B118": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B119": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B120": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B121": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B122": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B123": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B125": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B126": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B127": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B128": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B129": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B130": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B131": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": [("mon_shortcut_4",[[]])], "Dungeon": False, "Skipped": False},
        "B132": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B133": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B134": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B135": {"Chest_Score": 1, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B136": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B138": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B139": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B140": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B142": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B143": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B144": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B145": {"Chest_Score": 3, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B146": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B147": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B148": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B149": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B150": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B151": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B152": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B153": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B154": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B155": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B156": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B158": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B159": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B160": {"Chest_Score": 2, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B161": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B162": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B163": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": [("mon_shortcut_5",[[]])], "Dungeon": False, "Skipped": False},
        "B164": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B165": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B166": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B167": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B168": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B170": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B171": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B172": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B173": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B174": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B175": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B176": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B177": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B178": {"Chest_Score": 2, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B180": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B181": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B182": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B183": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B184": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B185": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B186": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B187": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B188": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B189": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B190": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B191": {"Chest_Score": 1, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B192": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B193": {"Chest_Score": 0, "Smiler": True,  "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B194": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B195": {"Chest_Score": 4, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B198": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B199": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B200": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B201": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B202": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B203": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B204": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B205": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B206": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B207": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B208": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B209": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B210": {"Chest_Score": 3, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B211": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B212": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B213": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B214": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B215": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B216": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B217": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B218": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B219": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B220": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B221": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B222": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B224": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B226": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B228": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B229": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B230": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B231": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B232": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B233": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B234": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B235": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B236": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B237": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B238": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B239": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B240": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B241": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B242": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B243": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B244": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B245": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B246": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B247": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B248": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B249": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B250": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B251": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B252": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B253": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B254": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "B255": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        }

RequiredSideBranes = {
        "room_add": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B025",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_eus": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B055",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_bee": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B071",[[("item",ItemNames.void_wings)]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_mon": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B111",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_tan": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B140",[[("item",ItemNames.void_sword),("idol","killer")]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_gor": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B162",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_lev": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B181",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_cif": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B224",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        }

OptionalSideBranes = {
        "mon_shortcut_1": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B023",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "mon_shortcut_2": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B053",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "mon_shortcut_3": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B109",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "mon_shortcut_4": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B167",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "mon_shortcut_5": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("B197",[[]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        "room_dis": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("dis_entrance",[[("item",ItemNames.void_wings),("item",ItemNames.void_sword)]]), "Shortcut": False, "Dungeon": False, "Skipped": False},
        }
        
        #dungeon dicts use the format {dungeon_name: [(brane_type, {floor_data}),(other_required_floor_for_dungeon_access)]}
Dungeons = {
        "Bee's Hole": [
            ("side", {"beehole_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": ("Bee's Hole", "B161"), "Skipped": False}})
            ],
        "Greed Zone": [
            ("side", {"greedzone_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": "Greed Zone", "Skipped": False}})
            ],
        "DIS": [
            ("side", {"dis_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": False, "Shortcut": False, "Dungeon": "DIS", "Skipped": False}})
            ]
        }

# for convenience, this is laoded instead of the normal Dungeons dict if shuffle floors is off
VanillaDungeonEntrances = {
        "beehole_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": ("Bee's Hole", "B161"), "Skipped": False},
        "greedzone_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": ("next",[[]]), "Shortcut": False, "Dungeon": "Greed Zone", "Skipped": False},
        "dis_entrance": {"Chest_Score": 0, "Smiler": False, "Interface": False, "Brand_Room": False, "Stairs": False, "Shortcut": False, "Dungeon": "DIS", "Skipped": False}
        }
# vanilla dungeons: Beehole, Greedzone, DIS, Hunter, Ninnie, White Void, Voided, Black Void, Elysium, Dev room, Lev's mind?

# dungeons required for the goal will be included regardless of exclusion settings